### ISSUE TITLE
TypeError: this.$body is undefined. also, Is this no longer maintained?

### ISSUE THREAD

**Issue by KrunchMuffin** [scruffles/BootstrapModalPopover#10]
I get this error when clicking on the element.
`TypeError: this.$body is undefined`
I was using the BS3 popover before I found this plugin.

**Comment by scruffles** [comment]
That sounds like a bs3 incompatibility.  The component only supported bs2 until a recent pull request.

I don't actively update this project.  It's unrelated to my current work, which is all in react/coffeescript.  I do accept pull requests though.
