### ISSUE TITLE
Use this for Bootstrap 3 

### ISSUE THREAD

**Issue by KrunchMuffin** [scruffles/BootstrapModalPopover#11]
http://plugins.krajee.com/popover-x

**Comment by assertnotnull** [comment]
I've updated it for Bootstrap 3 if anyone is interested
https://github.com/assertnotnull/BootstrapModalPopover
http://jsfiddle.net/assertnotnull/fvzhyz11/

**Comment by KrunchMuffin** [comment]
Thanks for doing that! Do you plan on maintaining it as well?

**Comment by assertnotnull** [comment]
I can't promise I can maintain it, it's just that I'm using it

**Comment by scruffles** [comment]
I updated my docs and demos page to use bootstrap 3, then merged these changes into mine.  I ended up having to roll back the change from position() to offset() on line 26.  There's probably something different about how I position my dialogs in my demo, but I haven't found it yet.  I can't get your fiddle working for some reason.  

If anyone has the need to change how that's positioned, I would appreciate a pull request that includes an additional example in the index.html.

**Comment by assertnotnull** [comment]
My bad. It works in firefox using position method but not chrome..
Offset works better

**Comment by assertnotnull** [comment]
In fact no, using offset is not working right in my project..
Screenshot coming

**Comment by assertnotnull** [comment]
![capture du 2015-11-05 09 24 46](https://cloud.githubusercontent.com/assets/821567/10970908/64c63c98-839f-11e5-86d4-b2c481727cd5.png)

**Comment by assertnotnull** [comment]
My fiddle was failing for chrome complaining of Mime type ('text/plain') not executable
I've updated it:
http://jsfiddle.net/assertnotnull/fvzhyz11/1/

**Comment by scruffles** [comment]
I assume the problem in your app is related to [Issue #3](https://github.com/scruffles/BootstrapModalPopover/issues/3).  I haven't been able to reproduce that.  I'd like to reproduce it in my [documentation](https://github.com/scruffles/BootstrapModalPopover/blob/master/index.html) ideally, but if you can reproduce it in fiddle, I can move it over.  I suspect it will be easy to fix once I have an example to play with.

**Comment by assertnotnull** [comment]
Yes it seems it's the same problem. Here the thing is `position` is relative to the parent while `offset` is relative to the document

**Comment by scruffles** [comment]
added it as an option.  there's a demo on the [homepage](http://scruffles.github.io/BootstrapModalPopover/)
