### ISSUE TITLE
Popup cant open on click anytime

### ISSUE THREAD

**Issue by dkedar** [scruffles/BootstrapModalPopover#12]
Hello 
I am using  bootstrap-modal-popover.js in my java Project, this is a grate plugin to show the content in Popup format.
I am facing one small Issue currently is that, when page is loaded and when I click on the link then popup is showing correctly, but when I click the like again it is not showing. alternate click it is showing, but not each click.
I don't know why? if any fix or solution please let me know.

**Comment by scruffles** [comment]
if you can create a demo (maybe in jsfiddle), I may be able to help
