### ISSUE TITLE
dialog position work only if the parent dialog is the window

### ISSUE THREAD

**Issue by jerome31** [scruffles/BootstrapModalPopover#3]
If the dialog (like <div id="popupBottom" class="popover">) is placed in a container with a position absolute, then the position of the dialog is misspositioned.

Du to the fact that the position of the dialog is calculated from the window, but in css it's placed from parent container of the dialog.

Exemple : http://jsfiddle.net/HjzPJ/5/

If the dialog is placed in the body, then it is well placed. But sometime, it is usefull to place the dialog near the target, for readability purpose.

If i understand, in this case, the position of the dialog must by calculated with the jQuery fonction .position() in replacement of .offset().

Here is a exemple with the remplacement in getPosition() : http://jsfiddle.net/HjzPJ/7/

in the second case, it is working only if the dialog et the target have same parent container for css position.

sorry for my english,

perhaps a option may be created, to specify if the position must be calculted form the window or from the target, or from something else.

I do not usually use github, if it can by done, it will be great.

**Comment by scruffles** [comment]
added a note to the readme.  I'll leave this open.  If anyone has a pull request (preferably with a demo in the readme) I would be happy to merge it.

**Comment by scruffles** [comment]
fixed with the option 'modal-position'.  see [the homepage](http://scruffles.github.io/BootstrapModalPopover/) for a demo
