### ISSUE TITLE
Cannot have multiple buttons that launch the same popover

### ISSUE THREAD

**Issue by flyer1** [scruffles/BootstrapModalPopover#8]
When I have multiple buttons that launch the same popover, I found that the second button I clicked on would show the popover off the screen (negative coords). 

It is happening b/c $this.data('modal-popover') stores the options that you pass in and even if you redefine those options just prior to showing the popover, it just pulls the first value from $.data() (which is for the wrong button). 

Not sure if I'm using the control wrong, but I modified the modalPopover (line 113 in the current src) where I force data to undefined when passing in options. This resets it so it's not pulled from $.data() and now it's working:

$.fn.modalPopover = function (option) {
...
            var data = typeof option == 'string' ? $this.data('modal-popover') : undefined; 

(Love this simple control btw! Thanks for making it)

**Comment by scruffles** [comment]
Thanks for the fix.  I know it's been a while.  I haven't been maintaining this component.  But since others are apparently still finding use for it, I made an example in the demo to test this and committed your fix.
